export enum ZoneMap {
    TATAOUINE_MEDNINE_KEBILI_TOZEUR,
    GAFSA_SIDIBOUZID_KASSERINE,
    SFAX_GABES_MAHDIA_MOUNASTIR_SOUSSE,
    KAIROUAN_SILIANA_EL_KEF,
    BEJA_JANDOUBA_BIZERTE,
  ZAGHOUAN_NABEUL_TUNIS,
    TUNIS
  }
